language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION="2.8.*@dev symfony/phpunit-bridge:~2.7"
    - php: 5.6
      env: SYMFONY_VERSION="3.0.*@dev"
    - php: 7.1
      env: SYMFONY_VERSION="3.*@dev"
    - php: 7.1
      env: SYMFONY_VERSION="4.*@dev"
  fast_finish: true

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update --prefer-dist

script: phpunit
